### ISSUE TITLE
门户一直登录失败

### ISSUE THREAD

**Issue by youngsteryuan** [xiazhongyv/PKUAutoSubmit_online#11]
Error:     raise Exception('门户登录失败')
Exception: 门户登录失败
Error: Process completed with exit code 1.

大佬请问这是咋回事呀

**Comment by Housyou** [comment]
如果以前可以运行，今天忽然不行了，怀疑是不是[和超时事出同因](https://github.com/Bruuuuuuce/PKUAutoSubmit/issues/38)？

这个bug太玄学了，不懂怎么修（

**Comment by xiazhongyv** [comment]
确实很玄学，我最近十几次自动运行也有一次失败了，我又手动运行就成功了，只能怀疑是报备网卡了（

**Comment by xiazhongyv** [comment]
或者手动登录确认下，有无人脸识别或者微信关注的提示框，这俩提示框也会导致登录失败

**Comment by xiazhongyv** [comment]
或者重新输入遍secrets确认用户名密码没输错 [捂脸]

**Comment by youngsteryuan** [comment]
> 或者手动登录确认下，有无人脸识别或者微信关注的提示框，这俩提示框也会导致登录失败

请问，那个显示各种 “余额 、未读邮件、待办事项”的对话框 需要取消吗

**Comment by xiazhongyv** [comment]
> 请问，那个显示各种 “余额 、未读邮件、待办事项”的对话框 需要取消吗

应该是不需要，我没取消但是能够正常运行
