### ISSUE TITLE
学校改版了一个出校事由然后失效了，能不能增加个直接调取上一次填写内容然后提交的逻辑？

### ISSUE THREAD

**Issue by xin-xiner** [xiazhongyv/PKUAutoSubmit_online#12]
就是不太知道页面里那个调取之前填写内容的按钮不能能程序直接调用？
能的话，能不能增加个直接调用两次那个按钮的选项？
这样的话，不论以后学校怎么改，只要“上次填写内容”的按钮还在，就都不会影响程序的运行

**Comment by xin-xiner** [comment]
然后之前昌平区的那个问题其实也就绕过了

**Comment by xin-xiner** [comment]
（说了这么多，其实我完全不懂 捂脸.jpg

**Comment by Housyou** [comment]
我在11月14日那次变更之后，“上次填写内容”不能提交，因为没有出入校事由这一项。

**Comment by xiazhongyv** [comment]
在更新之后，上次填写内容也是失效的。
以及还有这样的情况：我定时每周三天报备出校科研，但是周末我因为别的事由手动报备了一次，如果第二天忘记再以原来的科研理由重新报备，填写上次内容就会出现错误。现在海淀区疫情形势加紧，学校通知会审查报备内容，还是如实填写不发生内容错误比较好。

**Comment by xin-xiner** [comment]
@Housyou 这个是需要重新手动填写提交一次，然后就可以正常使用上次填写内容了
哈哈，我只是提议，就是多加个可能的提交方式，然后能够规避一些修改~反正我自己也不知道怎么写，再说再说

**Comment by Housyou** [comment]
你说得对，不过这样的话改动的部分可能不少（因为没有研究过“上次填写内容”的逻辑），而最近那次修改其实没什么复杂度。之后有版本更新大的话可以看看。
