### ISSUE TITLE
有一篇带照片和视频的详细教程

### ISSUE THREAD

**Issue by hayschan** [xiazhongyv/PKUAutoSubmit_online#13]
针对完全不懂 GitHub 和计算机的同学，可以看看这篇教程。《[北京大学出入校备案自动化（2021 版）](https://blog.haysc.tech/pku-auto-beian-2021/)》
如果 Repo 作者觉得合适的话，可以把链接放到 README 里。

**Comment by xiazhongyv** [comment]
感谢！
