### ISSUE TITLE
chromedriver版本问题

### ISSUE THREAD

**Issue by pkuloaf** [xiazhongyv/PKUAutoSubmit_online#18]
今天运行报错：
`This version of ChromeDriver only supports Chrome version 94`
`Current browser version is 96.0.4664.45 with binary path /usr/bin/google-chrome`

已经提交了修改，见#17

**Comment by RiRuby** [comment]
试了试运行正常，太优秀了

**Comment by RiRuby** [comment]
请问这个报错的原因是什么呢，看起来不是selenium的问题。是github更新了运行环境的chrome版本吗？

**Comment by pkuloaf** [comment]
> 请问这个报错的原因是什么呢，看起来不是selenium的问题。是github更新了运行环境的chrome版本吗？

嗯，应该就是Github Actions的运行环境更新了chrome版本

**Comment by James-Harden-13-R** [comment]
请问这个要怎么改呀，把新版本的文件放到原来的文件夹就可以了吗

**Comment by RiRuby** [comment]
> 请问这个要怎么改呀，把新版本的文件放到原来的文件夹就可以了吗

对，你也可以等xiazhongyv更新完pull一下

**Comment by James-Harden-13-R** [comment]
> > 请问这个要怎么改呀，把新版本的文件放到原来的文件夹就可以了吗
> 
> 对。如果不急你也可以等xiazhongyv更新完pull一下。

搞定了！感谢~

**Comment by Housyou** [comment]
我不了解google-chrome的更新频率怎么样，网上查了一下好像说6周就会更新一次，是否有必要参考一下这个同学一劳永逸的解决办法呢？https://github.com/Bruuuuuuce/PKUAutoSubmit/pull/40

**Comment by xiazhongyv** [comment]
ok merge了

**Comment by youngsteryuan** [comment]
太强啦

**Comment by xiazhongyv** [comment]
我试一下看能不能改成检测并自动下载最新driver，每六周更新一次也太惨了

**Comment by xiazhongyv** [comment]
哈哈哈现在已经不存在chromedriver目录了，改成用webdriver_manager自动下载了！
感谢 @Housyou

**Comment by xiazhongyv** [comment]
笑死，原来环境自带了对应版本的driver，根本不用下载，感谢 @pkuloaf
