### ISSUE TITLE
住在万柳，需要同时报备万柳出入校+燕园出入校

### ISSUE THREAD

**Issue by jwhsir** [xiazhongyv/PKUAutoSubmit_online#3]
请问：住在万柳，需要同时报备万柳出入校+燕园出入校，应该怎么设置呢？非常感谢！

**Comment by xiazhongyv** [comment]
首先，如果想要同时报备多个校区的话，可以使用PKUAutoSubmit的多配置文件功能，操作如下：
将 config.ini 文件复制若干份，分别重命名为 config+序号.ini 例如 config1.ini, config2.ini...并配置对应变量

另外，按照目前学校的报备系统，只需要在一个校区报备一次，当天就可以在所有校区多次出入，所以只要报备一次万柳就可以。

**Comment by jwhsir** [comment]
> 首先，如果想要同时报备多个校区的话，可以使用PKUAutoSubmit的多配置文件功能，操作如下： 将 config.ini 文件复制若干份，分别重命名为 config+序号.ini 例如 config1.ini, config2.ini...并配置对应变量
> 
> 另外，按照目前学校的报备系统，只需要在一个校区报备一次，当天就可以在所有校区多次出入，所以只要报备一次万柳就可以。

感谢回复！我试试！

**Comment by jwhsir** [comment]
成功了！非常感谢！
