### ISSUE TITLE
code run fail

### ISSUE THREAD

**Issue by Xing-Jin-99** [xiazhongyv/PKUAutoSubmit_online#30]
这个code还能用吗？几乎检查Q&A里面所有问题，但是code 还是 run fail了，qaq

**Comment by xiazhongyv** [comment]
secrets的五个字段都有填写吗，我看了下你的运行记录，完全没有运行起来代码，在传这五个参数时就报错了

**Comment by xiazhongyv** [comment]
感觉像是把这五个字段中的某一部分识别成参数名了，重新输入下ID PASSWORD MAIL_ADDRESS PHONE_NUMBER SENDKEY这五个字段，注意里面有没有除了数字英文和“@”之外的特殊字符，比如‘-’ ‘/’ ‘\’ ‘()’ ‘.’之类的，哪个字段有，就在填写时把哪个字段用引号包裹起来输入value一栏，并且确保里面没有空格。

**Comment by Xing-Jin-99** [comment]
您好！问题找到了，是因为之前SENDKEY字段含有空格，之前没注意到，现在可以运行了。十分感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiazhongyv/PKUAutoSubmit_online"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiazhongyv/PKUAutoSubmit_online] code run fail (Issue #30)





 
感觉像是把这五个字段中的某一部分识别成参数名了，重新输入下ID PASSWORD MAIL_ADDRESS PHONE_NUMBER SENDKEY这五个字段，注意里面有没有除了数字英文和“@”之外的特殊字符，比如‘-’ ‘/’ ‘\’ ‘()’ ‘.’之类的，哪个字段有，就在填写时把哪个字段用引号包裹起来输入value一栏，并且确保里面没有空格。
