### ISSUE TITLE
不能选昌平区？

### ISSUE THREAD

**Issue by xin-xiner** [xiazhongyv/PKUAutoSubmit_online#4]
测试海淀区是可以的
昌平区就会报错

或许是昌平区的点击的值不对？
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (82, 539). Other element would receive the click: <div class="el-scrollbar__bar is-horizontal">...</div>
  (Session info: headless chrome=95.0.4638.69)

选择居住地所在区    
Error: Process completed with exit code 1.

**Comment by xin-xiner** [comment]
我猜的哈，driver.find_element_by_xpath(f'//li/span[text()="{district}"]').click()
的时候，是能找到昌平区的

但是昌平区在那个列表里是需要滚动条拖动一下才能拉出来的，不然不显示

然后这里返回的位置是内部的位置，然后不滚动一下显示不出来，去点击时候就会报错

**Comment by xin-xiner** [comment]
看了一下，按照我猜的话，应该除了最开始几个“其他” 东城 西城 朝阳 丰台 石景山 海淀 门头沟之外
其他的区应该都会遇到这个问题？

**Comment by xin-xiner** [comment]
解决不了，我认输，看大哥你有没有解决方法了。星星先点了以示瑞思拜

**Comment by xiazhongyv** [comment]
selenium是这样的[捂脸]，等我有空写一下

**Comment by xin-xiner** [comment]
坐等大哥拯救。（不过问题不大，都自动报备了，就这种态度，填哪也没啥区别了……反正这申报记录…真会有人看吗 狗头.jpg

**Comment by xiazhongyv** [comment]
理论上并不会有人看23333
而且它的匹配算法是只要当天报备过，不管填的哪个区哪个校区哪个门，都可以出入所有校区的所有门2333
我曾经报备了燕园东门然后去了中关畅春和燕园东南西南门，都没事

**Comment by xin-xiner** [comment]
哈哈，是的，所以就既然就是个形式，那就是个形式 狗头.jpg (只不过昨天为了妥协，选了海淀清河街道，然后今天那一片就出了病例……哈哈哈，慌的一批，不过最后划到西三旗去了，不然不知道会不会被询问 捂脸

**Comment by chf12345** [comment]
yysy看作者的代码结构还是蛮清晰的，资瓷(个_个)

**Comment by xiazhongyv** [comment]
感谢 @12f23eddde 的PR，现在应该已经修复了
