### ISSUE TITLE
报备系统好像更新了

### ISSUE THREAD

**Issue by turbo-crazydragon** [xiazhongyv/PKUAutoSubmit_online#6]
多了一个进出校详细事由

**Comment by LaanChae** [comment]
确实

**Comment by Housyou** [comment]
已经提交了修改，见#7

**Comment by youngsteryuan** [comment]
> 已经提交了修改，见#7

太强了！！

**Comment by jwhsir** [comment]
> 已经提交了修改，见#7

太强了！！感谢

**Comment by xiazhongyv** [comment]
> 已经提交了修改，见#7

太强了！我今天抽空merge

**Comment by xiazhongyv** [comment]
已经更新啦，请重新Fork或者Fetch and merge upstream试一下~
更新之后不要忘记改config.ini以及workflow下的corn表达式哦
