### ISSUE TITLE
现在报备增加了个详细事由, 好像运行不了了.

### ISSUE THREAD

**Issue by iamjustalittlebit** [xiazhongyv/PKUAutoSubmit_online#9]

**Comment by xiazhongyv** [comment]
今天已经紧急更新啦，请重新Fork或者Fetch and merge upstream试一下~
更新之后不要忘记改config.ini以及workflow下的corn表达式哦

**Comment by xiazhongyv** [comment]
已经紧急更新啦，请重新Fork或者Fetch and merge upstream试一下~
更新之后不要忘记改config.ini以及workflow下的corn表达式哦

**Comment by xiazhongyv** [comment]
我这里看到你的仓库还是旧版本呜呜呜，先close掉这个issue了，如果有问题再来提新issue鸭
